export type WarningType =
  | "cave leech cluster"
  | "duck and cover"
  | "elite threat"
  | "exploder infestation"
  | "haunted cave"
  | "lethal enemies"
  | "low oxygen"
  | "mactera plague"
  | "parasites"
  | "regenerative bugs"
  | "rival presence"
  | "rock infestation"
  | "shield disruption"
  | "swarmageddon";